# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b649e1858db40bb07638178586e917f177873ece96451744f3f36c18a1d3c1c43298e076f5b58ebe68415d39b9ebb235d6aef7ae2e499079c8a11db096ac567

test:
  secret_key_base: 2193718049c375e1a63ac11c3398d736ca6a44df9994f7cfba257baec43c1199008a9e9f90a0cccdd0d62d6ebf7b7d775b909f5ec3ff4522e6832ab9a2802f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
